---
- hosts: dev
  tasks:
          - name: adding one user named raman
            user: name=raman password=redhat uid=1040 shell=/bin/bash group=wheel comment="RAMAN MD" generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
          - name: Copy file with owner and permissions
            copy: src=/etc/ansible/ansible.cfg dest=/home/raman/.ansible.cfg owner=raman group=raman 



          - name: call second yml file here
            import_tasks: /home/lv/second.yml


