- name: push welcome note to and manage node
  hosts: 'dev: !172.25.250.10'
  tasks:
          - name: push motd.j2 through template module
            template:
                    src: motd.j2
                    dest: /etc/motd
                    
